/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dev.nizarfadlan.tugas1;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Hashtable;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author nizar
 */
public class Tugas1 extends javax.swing.JFrame {
    public int mode = 0;
    public Hashtable listInggris = new Hashtable();
    public Hashtable listIndonesia = new Hashtable();
    public List<Hashtable> listElementWorld = new ArrayList<>();
    public List<String[]> dataList = new ArrayList<>(Arrays.asList(
        new String[]{"SATU", "ONE"},
        new String[]{"GAJAH", "ELEPHANT"},
        new String[]{"HARIMAU", "TIGER"}, 
        new String[]{"NASI", "RICE"}, 
        new String[]{"MERAH", "RED"}
    ));
    
    /**
     * Creates new form Tugas1
     */
    public Tugas1() {
        initComponents();
        
        listInggris.put("title", "ENGLISH INDONESIA DICTIONARY");
        listInggris.put("labelKataIndonesia", "Entry English Word");
        listInggris.put("labelKataInggris", "Indonesian Word");
        listInggris.put("buttonCari", "Search");
        listInggris.put("buttonHapus", "Clear");
        listInggris.put("buttonKeluar", "Exit");
        listInggris.put("buttonLihatData", "See Dictionary");
        listInggris.put("buttonSimpan", "Save");
        
        listIndonesia.put("title", "KAMUS INGGRIS-INDONESIA");
        listIndonesia.put("labelKataIndonesia", "Masukkan Kata Indonesia");
        listIndonesia.put("labelKataInggris", "Kata Inggrisnya");
        listIndonesia.put("buttonCari", "Cari");
        listIndonesia.put("buttonHapus", "Hapus");
        listIndonesia.put("buttonKeluar", "Keluar");
        listIndonesia.put("buttonLihatData", "Lihat Daftar");
        listIndonesia.put("buttonSimpan", "Simpan");
        
        listElementWorld.add(listIndonesia);
        listElementWorld.add(listInggris);
        
        this.setTitle((String) listElementWorld.get(mode).get("title"));
        buttonIndonesiaKeInggris.setSelected(mode == 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonModeGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelKataIndonesia = new javax.swing.JLabel();
        labelKataInggris = new javax.swing.JLabel();
        inputKata2 = new javax.swing.JTextField();
        inputKata1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataTabel = new javax.swing.JTable();
        labelDataKamus = new javax.swing.JLabel();
        buttonSimpan = new javax.swing.JButton();
        buttonLihatData = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        buttonCari = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonKeluar = new javax.swing.JButton();
        labelMode = new javax.swing.JLabel();
        buttonIndonesiaKeInggris = new javax.swing.JRadioButton();
        buttonInggrisKeIndonesia = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        labelKataIndonesia.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        labelKataIndonesia.setText("Masukkan Kata Indonesia");

        labelKataInggris.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        labelKataInggris.setText("Kata Inggrisnya");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelKataIndonesia, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(labelKataInggris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputKata1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                    .addComponent(inputKata2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKataIndonesia)
                    .addComponent(inputKata1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKataInggris)
                    .addComponent(inputKata2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        dataTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Indonesia", "Inggris"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(dataTabel);
        dataTabel.getAccessibleContext().setAccessibleName("");
        dataTabel.getAccessibleContext().setAccessibleDescription("");

        labelDataKamus.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        labelDataKamus.setText("Data Kamus");

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonLihatData.setText("Lihat Daftar");
        buttonLihatData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLihatDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(buttonSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonLihatData)
                .addGap(81, 81, 81))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDataKamus, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(buttonLihatData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelDataKamus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        buttonCari.setText("Cari");
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonKeluar.setText("Keluar");
        buttonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarActionPerformed(evt);
            }
        });

        labelMode.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        labelMode.setText("Dictionary Model");

        buttonModeGroup.add(buttonIndonesiaKeInggris);
        buttonIndonesiaKeInggris.setText("INDONESIA - INGGRIS");
        buttonIndonesiaKeInggris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDictionaryModelAction(evt);
            }
        });

        buttonModeGroup.add(buttonInggrisKeIndonesia);
        buttonInggrisKeIndonesia.setText("ENGLISH - INDONESIA");
        buttonInggrisKeIndonesia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDictionaryModelAction(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(buttonCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonKeluar))
                    .addComponent(buttonInggrisKeIndonesia)
                    .addComponent(buttonIndonesiaKeInggris)
                    .addComponent(labelMode))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCari, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(labelMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonIndonesiaKeInggris)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonInggrisKeIndonesia)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDictionaryModelAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDictionaryModelAction
        mode = buttonIndonesiaKeInggris.isSelected() ? 0 : 1;
        this.setTitle((String) listElementWorld.get(mode).get("title"));
        labelKataInggris.setText((String) listElementWorld.get(mode).get("labelKataInggris"));
        labelKataIndonesia.setText((String) listElementWorld.get(mode).get("labelKataIndonesia"));
        buttonCari.setText((String) listElementWorld.get(mode).get("buttonCari"));
        buttonHapus.setText((String) listElementWorld.get(mode).get("buttonHapus"));
        buttonKeluar.setText((String) listElementWorld.get(mode).get("buttonKeluar"));
        buttonLihatData.setText((String) listElementWorld.get(mode).get("buttonLihatData"));
        buttonSimpan.setText((String) listElementWorld.get(mode).get("buttonSimpan"));
    }//GEN-LAST:event_buttonDictionaryModelAction

    private void buttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonKeluarActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        inputKata1.setText("");
        inputKata2.setText("");
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonLihatDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLihatDataActionPerformed
        DefaultTableModel modelTable = (DefaultTableModel) dataTabel.getModel();
        modelTable.setRowCount(0);
        for (String[] data : dataList) {
            String[] dataListTemp = {data[0], data[1]};
            modelTable.addRow(dataListTemp);
        }
    }//GEN-LAST:event_buttonLihatDataActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
      String kataIdn = (mode == 0 ? inputKata1.getText().toUpperCase()  : inputKata2.getText().toUpperCase());
      String kataEng = (mode == 0 ? inputKata2.getText().toUpperCase() : inputKata1.getText().toUpperCase());

      boolean kataDitemukan = false;
      boolean invalidKata1 = false;
      for (String[] data : dataList) {
        if (data[0].equals(kataIdn) || data[1].equals(kataEng)) {
          kataDitemukan = true;
          invalidKata1 = data[mode].equals(mode == 0 ? kataIdn : kataEng);
          break;
        }
      }

      if(!kataDitemukan) {
        String[] dataListTemp = {kataIdn, kataEng};
        dataList.add(dataListTemp);

        DefaultTableModel modelTable = (DefaultTableModel) dataTabel.getModel();
        modelTable.addRow(dataListTemp);
        JOptionPane.showMessageDialog(
          rootPane,
          mode == 0 ? (kataIdn + "," + kataEng + " Berhasil ditambahkan ke Kamus") 
                    : (kataIdn + "," + kataEng + " Successfully added to Dictionary"),
          mode == 0 ? "Berhasil" : "Success",
          JOptionPane.INFORMATION_MESSAGE
        );
      } else {
        JOptionPane.showMessageDialog(
          rootPane,
          mode == 0 ? ((invalidKata1 ? (mode == 0 ? kataIdn : kataEng) : (mode == 0 ? kataIdn : kataEng)) + " Sudah ada di kamus") 
                    : ((invalidKata1 ? (mode == 0 ? kataIdn : kataEng) : (mode == 0 ? kataIdn : kataEng)) + " It's already in the dictionary"),
          mode == 0 ? "Kesalahan" : "Error",
          JOptionPane.ERROR_MESSAGE
        );
      }
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
      String kataCari = inputKata1.getText().toUpperCase();
      boolean inputNotValid = kataCari.equals("");

      if (!inputNotValid) {
        String found = (mode == 0 ? "TIDAK KETEMU!" : "NOT FOUND!");
        for (String[] data : dataList) {
          if (data[mode].equals(kataCari)) {
            found = data[mode == 0 ? 1 : 0];
            break;
          }
        }
          inputKata2.setText(found);
      } else {
        JOptionPane.showMessageDialog(
          rootPane,
          mode == 0 ? "Masukkan kata yang dicari!" : "Enter the word you are looking for!",
          mode == 0 ? "Kesalahan" : "Error",
          JOptionPane.ERROR_MESSAGE
        );
      }
    }//GEN-LAST:event_buttonCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tugas1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCari;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JRadioButton buttonIndonesiaKeInggris;
    private javax.swing.JRadioButton buttonInggrisKeIndonesia;
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JButton buttonLihatData;
    private javax.swing.ButtonGroup buttonModeGroup;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JTable dataTabel;
    private javax.swing.JTextField inputKata1;
    private javax.swing.JTextField inputKata2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDataKamus;
    private javax.swing.JLabel labelKataIndonesia;
    private javax.swing.JLabel labelKataInggris;
    private javax.swing.JLabel labelMode;
    // End of variables declaration//GEN-END:variables
}
